# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"f1score": "00_utils.ipynb",
         "df_preproc": "00_utils.ipynb",
         "load_data": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://{user}.github.io/anomaly/"

git_url = "https://github.com/{user}/anomaly/tree/{branch}/"

def custom_doc_links(name): return None
